name: New Lab Member
description: Add a new lab member to the overview board.
title: "[Name]"
projects: ["slolab/2"]
body:
  - type: dropdown
    id: role
    attributes:
      label: Role
      multiple: false
      description: Can be any of intern, PhD, Postdoc, Staff, Admin, or PI.
      options:
        - Intern
        - PhD
        - Postdoc
        - Staff
        - Admin
        - PI
    validations:
      required: true
  - type: textarea
    id: research_interests
    attributes:
      label: Research Interests
      description: A paragraph on the research interests of the lab member.
    validations:
      required: true
  - type: textarea
    id: professional_career
    attributes:
      label: Professional Career
      description: A table of the professional career of the lab member.
    validations:
      required: true
  - type: textarea
    id: education
    attributes:
      label: Education
      description: A table of the education of the lab member.
    validations:
      required: true
